### ISSUE TITLE
Add a way to find Div dimensions

### ISSUE THREAD

**Issue by DataJuggler** [EdCharbeneau/BlazorSize#13]
I am trying to write this myself and not getting very far, but it would be a nice feature for Blazor users in my opinion.

And I have a question about your Read Me File Docs:

Below you test for 'Is Small Media', and if true you display a Full Data Grid on Is Small Media.

Shouldn't this be !IsSmallMedia?

    @if (IsSmallMedia)
    {
        //    Display a full data grid on larger devices   
    }
    else 
    {
        //     Display a card layout on small devices
    }

Thanks if you have time or feel it is a good fit for your project, it doesn't look very difficult:

Something like

    function GetRectangle(divName)
    {
        var elem = document.getElementById(divName);
        if (elem)
        {
            var rect = elem.getBoundingClientRect();
            return rect;
        }
    }

**Comment by EdCharbeneau** [comment]
@DataJuggler Thanks for the question.

I split the comment re: docs into a separate issue: https://github.com/EdCharbeneau/BlazorSize/issues/14

This is something that might be a good addition as an add-on. Ex: BlazorSize.Utilities keeping it optional.

While I do continue to support BlazorSize, it may take time before I'm able to add new features. This all depends on my current workload.

**Comment by DataJuggler** [comment]
Thanks for the reply. I meant to come back here and tell you I was able to figure it out.

window.BlazorJSFunctions =
{
    showPrompt: function (message)
    {
        return prompt(message, 'Type anything here');
    },
    GetElementHeight: function (name)
    {
        return document.getElementById(name).offsetHeight;
    },
    GetElementWidth: function (name)
    {
        return document.getElementById(name).offsetWidth;
    }
};

And this C# call:

// get the height and width
int height = await jsRuntime.InvokeAsync<int>("BlazorJSFunctions.GetElementHeight", name);
int width = await jsRuntime.InvokeAsync<int>("BlazorJSFunctions.GetElementWidth", name);
              
// set the size of the rectangle
rectangle = new Rectangle(0, 0, width, height);

I tried to find a way to do it one call, but I couldn't get the jsRuntime.InvokeAsync<Rectangle> to work.

Amazingly all my graphics code works and I was able to figure out approximately the pixel that was clicked on.

Thanks again for the reply. I am glad I got my feet web with JavaScript so I can do some things Blazor doesn't have out of the box.

You can close this thread.

**Comment by EdCharbeneau** [comment]
As long as you have a JSON serializeable object you can pass it between the JS > C# boundary. You may want to try something like this.

```
Rectangle rec = await jsRuntime.InvokeAsync<Rectangle>("BlazorJSFunctions.GetElementSize", name);
```

```
GetElementSize: function (name)
{
  let elm = document.getElementById(name)
  return { height: elm.offsetHeight, width: elm.offsetWidth };
},


```

**Comment by EdCharbeneau** [comment]
I stumbled on this polyfill today. This might be something worth adding to BlazorSize.

https://juggle.studio/resize-observer/

**Comment by DataJuggler** [comment]
That looks interesting. By the name of site it sounds like I might be related.

**Comment by EdCharbeneau** [comment]
I feel like this is out of scope due to the broad range of possible definitions of "element size". Element size may include: scroll, padding, margin, and border. Attempting to resolve all of these and make sense of a "true size" feels too broad for a tool that detects if a media query is present, or a resize has occurred.

This is great documentation though, my suggestion is to interop with the polyfill linked above.
