### ISSUE TITLE
Enhance ResizeListener and with MediaQuery like API

### ISSUE THREAD

**Issue by EdCharbeneau** [EdCharbeneau/BlazorSize#16]
Should ResizeListener be removed and replaced with a new API that behaves more like the MediaQueryList & MediaQuery component?

**Comment by EngstromJimmy** [comment]
I am using the ResizeListener to hide columns in a Grid (if the windows is to small to show all the data).
For most cases I think a mediaquerylist would probably do the trick, in my case though I need to be notified when the windows changes size regardless of what size it changes to.

**Comment by EdCharbeneau** [comment]
Is the current API easy enough to use? Or would you favor a drop in component that can raise a change event?

**Comment by EdCharbeneau** [comment]
```
<ResizeManager>
    <ResizeListener @bind-Window="windowSize"/>
    <ResizeListener WindowChanged="@((window) => Foo(window.Width, window.Height)"/>
</ResizeManager>
```

**Comment by EngstromJimmy** [comment]
I think the API is easy enough.
Personally I prefer components to render something, in this case would only have functionality, I rather have services/injected instances for that.

**Comment by EdCharbeneau** [comment]
> Personally I prefer components to render something

Agreed. The reason I chose this path for the MediaQuery component was "ease-of-use". It was easier to use a component than to require users to manually add DI, init, and dispose methods. I fought the framework and the framework won.
