### ISSUE TITLE
Mobile?

### ISSUE THREAD

**Issue by ofrades** [EdCharbeneau/BlazorSize#18]
Any chance getting the library to work for mobile? The resize works very well but when in mobile it does not.

`[BlazorSize] matchMedia "(max-width: 575.98px)": false` when in mobile

`[BlazorSize] matchMedia "(max-width: 575.98px)": true` when resizing by hand

**Comment by EdCharbeneau** [comment]
Can you provide a sample of your code?

Also, try the MediaQuery component it's much more efficient.

**Comment by ofrades** [comment]
I have refactored to include the MediaQuery instead of what I had, but the behavior persists.
In Program I have this:
 
```
          builder.Services.AddResizeListener(options =>
            {
                options.ReportRate = 300;
                options.EnableLogging = true;
                options.SuppressInitEvent = false;
            });
```
And in the MainLayout.razor
```
<MediaQueryList>
    <MediaQuery Media="@Breakpoints.SmallDown">
      <Matched>
          <Navbarbottom />
     </Matched>
     <Unmatched>
         <Navbartop />
     </Unmatched>
   </MediaQuery>
  
    <div class="main">
        <div class="content">
            @Body
        </div>
    </div>

    <Footer />

  </MediaQueryList>$
```

The idea is to have one navbar in the top when not on mobile and another one just for mobile.

**Comment by EdCharbeneau** [comment]
Server Blazor or Wasm?

**Comment by ofrades** [comment]
Wasm

**Comment by EdCharbeneau** [comment]
1. Remove the section of code from your program.cs this is only required if you need direct access to the browser's resize event.
2. I was unable to reproduce the error. This means it is likely something to do with something specific to your project or how you are testing the application.

- If the test is failing on a specific mobile device, or browser then it's possible that the device/browser is reporting the wrong media query value. Please see: https://caniuse.com/#feat=matchmedia (Apple products are notoriously fussy with media queries).

I tested using both the Blazor Wasm and Blazor Wasm (hosted) templates using the following code.

**index.html**
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>BlazorApp15</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/app.css" rel="stylesheet" />
</head>

<body>
    <app>Loading...</app>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="_content/BlazorPro.BlazorSize/blazorSize.min.js"></script>
</body>

</html>
``` 
**index.razor**
```razor
@page "/"
@using BlazorPro.BlazorSize

<MediaQueryList>
    <MediaQuery Media="@Breakpoints.SmallDown">
        <Matched>
            <h1>Small</h1>
        </Matched>
        <Unmatched>
            <h1>Not Small</h1>
        </Unmatched>
    </MediaQuery>
</MediaQueryList>
```

I used chrome developer tools to test the app by selecting the mobile simulator. You can see a video of the test below.

https://1drv.ms/v/s!Ak8aQRebrTvWsZwwnqo_RdN5GqiwhQ

**Comment by ofrades** [comment]
Thank you @EdCharbeneau , that works.

**Comment by EdCharbeneau** [comment]
Great!
