### ISSUE TITLE
`MediaQueryList.Initialize()` lacks a call to `MediaQueryChanged()` when cache is already loaded

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [EdCharbeneau/BlazorSize#20]
Hi there,

I have been debugging an UI update issue seemingly related to `BlazorSize` and pinned it down to the cache implementation in `MediaQueryList`. Let me explain how to reproduce this.

1. create a Blazor server-side application
2. add `MediaQueryList` to `MainLayout.razor`
   ```
   <MediaQueryList>
     <MediaQuery Media="@Breakpoints.SmallDown" @bind-Matches="..." />
     ...
   </MediaQueryList>
   ```
3. create page 1 with a `MediaQuery` having the same `Media` parameter as used in `MainLayout.razor` like
   ```
   <MediaQuery Media="@Breakpoints.SmallDown">
     <Matched>
       <strong>Breakpoint matched</strong>
     </Matched>   
   </MediaQuery>    
   ```
4. create page 2, can be a blank one, it doesn't matter really
5. run application and set horizontal resolution < 768px
6. navigate to page 2, refresh the whole app in browser by pressing F5
   - now the cache is reloaded with an entry holding `SmallDown` queries, these queries get notified by a call to `MediaQueryChanged` in the process, content is rendered correctly
7. now navigate to page 1 by using the blazor navigation menu
   - cache is again iterated in `MediaQueryList.Initialize()`
   - cache holds an entry for `SmallDown` queries already
   - the query passed as parameter (created in step 3) is not notified due to the outer condition `if (cache.Value == null) { ... }` 
   - `Breakpoint matched` will not be displayed but it should be as the breakpoint is clearly hit (see resolution setting in step 5)

We can fix this by adding an else path in `MediaQueryList.Initialize()` ....

```
public async Task Initialize(MediaQuery mediaQuery)
{
    ...
    if (cache.Value == null)
    {
        ...
    }
    else
    {
        mediaQuery.MediaQueryChanged(cache.Value);
    }
}
```

... but we also need to update cache.Matched first I think. This would surely require extending `blazorMedia.ts` as I cannot find a function in `blazorMedia.ts` that just calls `window.match` to get the required value.

What do you say? Would you accept an PR for this change?

So lonG
Daniel

**Comment by EdCharbeneau** [comment]
This is great, thanks for taking it upon yourself to fix the issue. 🥇 

I'll review this quickly and merge. I'll update the NuGet package as well.
