### ISSUE TITLE
NullReferenceException in `MediaQueryList.RemoveQuery()`

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [EdCharbeneau/BlazorSize#22]
Hi there,

in `MediaQueryList.RemoveQuery()` the line `bool byMediaProperties(MediaQueryCache q) => q.Value?.Media == mediaQuery.InternalMedia.Media;` might cause an NullReferenceException when Value is `null`.

I get this exception quite frequently.

I will provide a PR.

So lonG
Daniel

**Comment by EdCharbeneau** [comment]
Your updates are part of the NuGet package now. You can switch to the 2.1 version of the NuGet feed in your projects if you wish to use the public feed.

**Comment by ViRuSTriNiTy** [comment]
Thank you, much apprechiated!
