### ISSUE TITLE
NuGet package version 2.1.0 causes TS18003 on compile

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [EdCharbeneau/BlazorSize#24]
Hi there,

you have lately updated the NuGet package to `2.1.0` to include #21 and #23. Many many thanks for that.

Now when I update the package to `2.1.0` I get the following error when compiling my project:

`TS18003 Build:No inputs were found in config file ...tsconfig.json`

Comparing `2.0.2` to `2.1.0` in `Dependencies` > `Packages` node of Visual Studio  I noticed that `2.1.0` it is targeting .NET Standard 2.0 **and** it includes a `tsconfig.json` file now. Is this a mistake in the packaging process or is this intended?

For the time being I have to include `<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>` in my `.csproj`. This solution was posted here:

https://stackoverflow.com/a/52926742/3936440

What do you say?

So lonG

Daniel

**Comment by EdCharbeneau** [comment]
Sorry, I'll try to fix that asap. There was a process that initially stopped this config file from entering the NuGet package. Something must have changed in the project or updates to .net that caused a regression.

I'll need to find the cause and upload a new version.

**Comment by EdCharbeneau** [comment]
Please try https://www.nuget.org/packages/BlazorPro.BlazorSize/2.1.1/

If this works I'll close the issue. Thank you!

**Comment by ViRuSTriNiTy** [comment]
Works like a charm now! Thank you, closing this.

**Comment by EdCharbeneau** [comment]
I wanted  to alert you to a new release 2.2.0. I found some regressions in the previous release that may impact stability. It's all fixed in 2.2.0. Please let me know if you encounter any issues.

**Comment by ViRuSTriNiTy** [comment]
@EdCharbeneau Thanks for your effort but the new version breaks some previously working stuff. I think this is caused by your lost change commit where you merged the else block to the wrong nesting level, see:

https://github.com/EdCharbeneau/BlazorSize/commit/f867ddb7d413dcb9644a7b25cc7dc22970522a28#diff-cabbf846fae5c7995ce72035e56880c1R85

The original change added the else block one level up:

https://github.com/EdCharbeneau/BlazorSize/commit/602ca8ba0993cd8c8f582defafb5d43c394bc7f8

I think this might also explain #25
