### ISSUE TITLE
MediaQuery stopped working for me in 2.2.0

### ISSUE THREAD

**Issue by jdcrutchley** [EdCharbeneau/BlazorSize#25]
I have a custom data grid with columns I make visible via a MediaVisibility parameter of type string like so:

```
<DataGridColumn TItem="MyApp.UserData" 
                    Title="Email" 
                    Field="@(u => u.Email)"
                    MediaVisibility="@Breakpoints.MediumUp"/>
```

Then I use that in my data grid component to selectively render columns like this:

```
@foreach (DataGridColumn<TItem> column in Columns)
                                {
                                    <MediaQuery Media="@column.MediaVisibility">
                                        <Matched>
                                            <td>
                                                @column.Render(item)
                                            </td>
                                        </Matched>
                                    </MediaQuery>
                                }
```

This worked fine in 2.1.1 and I was able to see columns appear/disappear as I resized my window.  In 2.2.0 no columns are rendered at all, even at max width.  

Has usage of MediaQuery changed?

**Comment by ViRuSTriNiTy** [comment]
@jdcrutchley Could you please verify whether changes from https://github.com/EdCharbeneau/BlazorSize/pull/27 will fix your issue?

**Comment by EdCharbeneau** [comment]
@jdcrutchley Possibly a issue with the latest update. Pushing a new version shortly.

**Comment by EdCharbeneau** [comment]
The fix was uploaded.

Please update to 2.3.0 when NuGet makes it available. https://www.nuget.org/packages/BlazorPro.BlazorSize/2.3.0 

Clear your browser cache just in case.

Try your project again and let me know if you're still experiencing an issue.

**Comment by EdCharbeneau** [comment]
Feel free to re-open the issue if the problem persists.

**Comment by jdcrutchley** [comment]
I was able to try the new version late last night and it worked.  Thank you!
