### ISSUE TITLE
MediaQuery quits working after you use a NanLink to go to another page.

### ISSUE THREAD

**Issue by JimWilcox3** [EdCharbeneau/BlazorSize#28]
This example is my MainLayout.razor:

    @inherits LayoutComponentBase

<MediaQueryList>
    <div class="sidebar">
        <NavMenu />
    </div>

    <div class="main">
        <MediaQuery Media="@Breakpoints.SmallDown">
            <Matched>
                <LoginDisplay />
            </Matched>
            <Unmatched>
                <div class="top-row px-4">
                    <LoginDisplay />
                </div>
            </Unmatched>
        </MediaQuery>

        <div class="content px-4">
            @Body
        </div>
    </div>
</MediaQueryList>

It works fine as long as you go to the main page and stay there.  If you shrink the width to make it reformat and click a NavLink then click back to the Home NavLink, 
   ` <MediaQuery Media="@Breakpoints.SmallDown"> `
is always unmatched.  If you increase the width to make it reformat then shrink the width, it will start working again.  I am trying to make my web site work on a phone and there is no way to increase and decrease the width on a phone.  You can go to my app at https://estimate.aimovers.com/estimate if you want to see it in action.  I have several
    `<MediaQuery Media="@Breakpoints.SmallDown"> `
on the main page and on the Extra Stops page.  There may already be a way around this.  Please let me know.

Thanks,
Jim

**Comment by JimWilcox3** [comment]
Version 2.3.0 Fixed this problem.

**Comment by EdCharbeneau** [comment]
Excellent, thanks for following up.

**Comment by ViRuSTriNiTy** [comment]
Side note: sounds like it's the same issue as #20 hence already fixed
