### ISSUE TITLE
.Net 5.0 Compatibility

### ISSUE THREAD

**Issue by roysurles** [EdCharbeneau/BlazorSize#30]
Is there an ETA for making this compatible with .Net 5.0?

**Comment by EdCharbeneau** [comment]
AFAIK it should be ok to use with .NET 5.0. However, this is a good reminder for me to test it.

**Comment by roysurles** [comment]
You are correct. My mistake. This package works as expected with .Net 5.0 RC1.... Thanks

**Comment by EdCharbeneau** [comment]
Confirmed. Tested with .NET 5.0 and works.
