### ISSUE TITLE
Cancel Window Resize or Resize Window

### ISSUE THREAD

**Issue by JimInNC** [EdCharbeneau/BlazorSize#36]
I am new to BlazorSize.  I have it working to detect a window resize by the user.  However, if the user resizes too small, I want to resize the window back to 1024 x 768.  It doesn't seem that calling JSInterop works for this.  Is there a way to resize the window using BlazorSize?  I'm using Chrome.  Thanks.

**Comment by EdCharbeneau** [comment]
It's my understanding that this is not possible due to concerns over abuse.

Please see: https://developer.mozilla.org/en-US/docs/Web/API/Window/resizeTo

> Note: It's **not possible** to resize a window or tab **that wasn’t created by window.open()**. It's also **not possible** to resize **when the window has multiple tabs**.

Closing because this is expected browser behavior per MDN. Sorry I couldn't help.

**Comment by JimInNC** [comment]
Hi Ed - thanks for the response.  My solution was to use the
ResizeListener.  When that fires, I call JSRuntime to resize my elements.
Works well.  Thanks.
