### ISSUE TITLE
Cannot provide a value for property 'MqService' when prerendering Blazor WASM

### ISSUE THREAD

**Issue by darkstormdesigns** [EdCharbeneau/BlazorSize#43]
Version: 3.2.0+ now giving this error (detailed below) in Blazor WASM
However changing back to version 3.1.0 with no code changes works ok.

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Cannot provide a value for property 'MqService' on type 'BlazorPro.BlazorSize.MediaQueryList'. There is no registered service of type 'BlazorPro.BlazorSize.IMediaQueryService'.
         at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass6_0.

Server's Startup.cs has
            services.AddResizeListener(options =>
            {
                options.ReportRate = 300;
                options.EnableLogging = false;
                options.SuppressInitEvent = true;
            });

Client Program.cs
            builder.Services.AddResizeListener(options =>
            {
                options.ReportRate = 300;
                options.EnableLogging = false;
                options.SuppressInitEvent = true;
            });

**Comment by EdCharbeneau** [comment]
In BlazorSize 3.2.* a service was added for those who may be unit testing components using BlazorSize. To register the service use:

'services.AddMediaQueryService();'

AddResizeListener is a service for using the window resize event.

**Comment by EdCharbeneau** [comment]
TODO: Needs documentation

**Comment by EdCharbeneau** [comment]
Fixed: https://github.com/EdCharbeneau/BlazorSize/wiki#configure-di

**Comment by hhyyrylainen** [comment]
Would be nice to add that extra bit of documentation to the main readme (https://github.com/EdCharbeneau/BlazorSize) as well, as I ran into this issue while following the steps in that.
