### ISSUE TITLE
Code Landing page needs to be updated

### ISSUE THREAD

**Issue by alwilton** [EdCharbeneau/BlazorSize#46]
I was looking for an issue with a Media Query error and I eventually found the answer, but not where I expected. When you search for this project you land on the [Code Page](https://github.com/EdCharbeneau/BlazorSize)  but it looks like that hasn't been updated for since last August while a tremendous amount of work has happened since. It shows the current version as 2.2.0 vs. the real current version of 3.2.1 and it does not mention adding the services.AddMediaQueryService(); and I'm sure there are many more updates missing as well.

Other than that thank you so much for the great work!

**Comment by EdCharbeneau** [comment]
Oh, wow, that's something I totally overlook. Thanks for bringing it to my attention so I can fix it asap.

Best wishes,
Ed

**Comment by EdCharbeneau** [comment]
- [x] Release added for 3.2.1
- [x] Docs reflect the DI service added to 3.2.1
