### ISSUE TITLE
With .net 5.0 constant errors from BlazorSize

### ISSUE THREAD

**Issue by longhornleads** [EdCharbeneau/BlazorSize#51]
Now I get repeated errors from BlazorSize saying:

Error: Microsoft.JSInterop.JSException: dotnet reference was not found in the collection of media query lists
Error: dotnet reference was not found in the collection of media query lists
    at BlazorSizeMedia.getMediaQueryListById

This just started happening when I migrated the app service to .NET 5.0.

**Comment by EdCharbeneau** [comment]
https://github.com/EdCharbeneau/BlazorSize#configure-di

With 3.2.1 a new service is required. This was added to expand BlazorSize's ability to support testing.

**Comment by longhornleads** [comment]
Yes, I added that but the error continues to take place.

**Comment by EdCharbeneau** [comment]
Can you post an example from where the code is throwing the error?

**Comment by EdCharbeneau** [comment]
Here is a working sample in .NET 5.0

https://github.com/EdCharbeneau/BlazorSizeTroubleshoot

I'm unable to reproduce the problem, but this is a fresh .NET 5 project.

> This just started happening when I migrated the app service to .NET 5.0.

Maybe there's something in migrating that I cannot reproduce. What did you migrate from exactly? .NET 3.1? Server > Wasm?

**Comment by longhornleads** [comment]
It might be easiest for me to send a link privately to the app that has the issue as I have verbose logging going so it shows the error. I think it might be possible that I have too many components on the page that all have a MediaQueryList. I might need to move that up a level and pass params to the child components.

**Comment by EdCharbeneau** [comment]
> Microsoft.JSInterop.JSException: dotnet reference was not found in the collection of media query lists

This usually occurs when something is disposed outside the scope of BlazorSize. Which shouldn't actually be able to happen. I have an e2e test that checks for this scenario. I'm trying to understand how this can happen. If components are deeply nested, it's possible there's some sort of race condition where the parent is disposed before the child.
