### ISSUE TITLE
Wiki/Docs need updating

### ISSUE THREAD

**Issue by robalexclark** [EdCharbeneau/BlazorSize#59]
I was getting an error with getting this to work from your wiki examples, the services need configuring as follows:

            services.AddScoped<IResizeListener, ResizeListener>();
            services.AddScoped<IMediaQueryService, MediaQueryService>();

not as specified in the wiki page

**Comment by EdCharbeneau** [comment]
Thanks, I did find a typo on the version number.

The method defined in the Wiki works though. Make sure you're on the latest version and have the namespace imported.

You can see the method is just shorthand for what you're using.
https://github.com/EdCharbeneau/BlazorSize/blob/master/BlazorSize/Configuration/ServiceCollectionExtensions.cs#L28
