### ISSUE TITLE
.NET 6 support

### ISSUE THREAD

**Issue by famda** [EdCharbeneau/BlazorSize#66]
Hey,

Has this library support for .NET 6?
Is it possible to have it targeted for .NET 6 ?

Thanks in advance.

**Comment by ViRuSTriNiTy** [comment]
A search in advance could have helped, see #64

**Comment by famda** [comment]
I'm glad you're able to help but, in fact, that issue is not answering my question.

**Comment by magajohn** [comment]
I'm also patiently waiting on a .NET 6 update. Hoping for it to come soon. Thanks for all the hard work

**Comment by EdCharbeneau** [comment]
Thanks for your interest. The update will be pushed to NuGet within the next 24 hours. I'm currently away from the office.

Thank you all.

**Comment by Peter-Simpson** [comment]
Thanks Ed, I've hit the same issue and will appreciate an update.

Best wishes, Peter

**Comment by EdCharbeneau** [comment]
BlazorSize 6.0 has been uploaded to NuGet and the feed should update shortly.

** Breaking Changes **

BlazorSize 6.0 is not compatible with .NET 5.0. If you wish to use BlazorSize with .NET 5.0 please use the previous version of BlazorSize.

bUnit tests have been moved to another package and require a separate install.
