### ISSUE TITLE
Failed to fetch dynamically imported module:

### ISSUE THREAD

**Issue by paburgos** [EdCharbeneau/BlazorSize#71]
Hi,

I have a weird behavior when I change from "ASPNETCORE_ENVIRONMENT": "Development" to "ASPNETCORE_ENVIRONMENT": "Staging" This is the error:

> Microsoft.AspNetCore.Components.Web.ErrorBoundary: Warning: Unhandled exception rendering component: Failed to fetch dynamically imported module: https://localhost:44303/_content/BlazorPro.BlazorSize/blazorSizeMediaModule.js TypeError: Failed to fetch dynamically imported module: https://localhost:44303/_content/BlazorPro.BlazorSize/blazorSizeMediaModule.js
> 
> Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:44303/_content/BlazorPro.BlazorSize/blazorSizeMediaModule.js TypeError: Failed to fetch dynamically imported module: https://localhost:44303/_content/BlazorPro.BlazorSize/blazorSizeMediaModule.js at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args) at BlazorPro.BlazorSize.MediaQueryService.CreateMediaQueryList(DotNetObjectReference`1 dotNetObjectReference) at BlazorPro.BlazorSize.MediaQueryList.OnAfterRenderAsync(Boolean firstRender) at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Do you know what might be the issue?

**Comment by EdCharbeneau** [comment]
It looks like static web assets are not included when the environment is set to staging.

Here are a few resources that my help:

https://stackoverflow.com/questions/66430714/when-aspnetcore-environment-changed-to-anything-but-development-blazor-app-d

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments

**Comment by paburgos** [comment]
Thank you so much @EdCharbeneau it worked!

**Comment by whoks-pedro** [comment]
Hi @paburgos 

Could you please describe what you have done to fix this?
I've added the UseStaticWebAssets() to the builder but I'm still getting the same error message.

I'm using Heroku and jincod's buildpack (https://github.com/jincod/dotnetcore-buildpack).
Still not sure if it is an issue with the buildpack or with BlazorSize.

Thank you.
