### ISSUE TITLE
blazorSize.js not found

### ISSUE THREAD

**Issue by DrTekno** [EdCharbeneau/BlazorSize#72]
### Environment: 
WASM and .NET6.
Debugging : updated Chrome and VSCode.

### Problem
I have MediaQueryList always null so i have added
` <script src="_content/BlazorPro.BlazorSize/blazorSize.js"></script>`
to my '.cshtml' file but still the file cant be found.

![image](https://user-images.githubusercontent.com/33718346/149167125-f4908fcf-fa9b-463f-952b-aedb0a4e5f6c.png)

My question is : Should the file be generated in the bin when build the application? 
Because is not my case and i've seen is hard coded here:
https://github.com/EdCharbeneau/BlazorSize/blob/net6/BlazorSize/MediaQuery/MediaQueryService.cs#L16

Thanks

**Comment by EdCharbeneau** [comment]
If you're on the latest version of BlazorSize you don't need the script tag. The latest version imports the script using modual imports.

Does this error occur normally? Is that why you're adding the script?

**Comment by EdCharbeneau** [comment]
Please make sure you have the service added to DI, and a MediaQueryList component at the root level.

**Comment by DrTekno** [comment]
Yes i've added '.AddMediaQueryService()' to DI, and 'MediaQueryList' component at the root level but without the script tag i've this error

![image](https://user-images.githubusercontent.com/33718346/149295502-11db23e7-63a3-4907-8464-3358cbbbc7a0.png)

**Comment by EdCharbeneau** [comment]
Any chance you can share a complete project or sample that has this issue?

**Comment by DrTekno** [comment]
The project is quite complex and i have finally found another solution but aniway thank you for your suggestions.

**Comment by juangallostra** [comment]
@EdCharbeneau I'm currently facing the same issue when trying to use BlazorSize. I have some other custom packages that are also raising this type of error after migrating to .NET 6.0. 

Haven't solved the issue myself yet, but here is some useful info I've found so far:
* https://github.com/dotnet/sdk/issues/19474
* https://devblogs.microsoft.com/dotnet/build-client-web-assets-for-your-razor-class-library/

![image](https://user-images.githubusercontent.com/9968427/152147078-ec32c442-dbb6-4c50-b1fb-8cb22fca6680.png)

**Comment by EdCharbeneau** [comment]
What I can't figure out is when this happens to a very specific minority of users. If you download the .nupkg file and rename it to .zip, you'll see that the required JavaScript assets are included where they belong.

**Comment by EdCharbeneau** [comment]
Maybe related to: https://github.com/EdCharbeneau/BlazorSize/issues/71#issuecomment-1029222043

**Comment by dennisrahmen** [comment]
@EdCharbeneau for me it's working fine while debugging.
But after publishing I get the same error as @juangallostra.

**Comment by juangallostra** [comment]
@EdCharbeneau release 6.1.2 fixed the problem for me. I was testing locally on windows (had no problems) but deploying from a Docker Image running Linux.

**Comment by EdCharbeneau** [comment]
@juangallostra thanks for following up

**Comment by sholman** [comment]
I've installed 6.1.2 and am getting this error. I can see the staticwebfiles in the nuget package but they're not being deployed on publish

**Comment by EdCharbeneau** [comment]
Can you double check this in your server's build process please?
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0#serve-files-in-web-root

**Comment by sholman** [comment]
> This issue was originally caused by Linux systems because they are case sensitive. One of the JavaScript files used an uppercase character in the file, but lower case in the C# codebase. The issue was fixed in 6.1.2.
> 
> Is there any way you're caching an old version? or the server is on a different version?
> 
> Is the server Linux?

Hi Ed, no, running on Windows. Same issue occurs on live app service and staging deployment slot.

**Comment by joepvtl** [comment]
Hi @sholman, what happens if you try to acces the file directly? And what happens when you do a Shift + F5, are you able to see the contents of the file then?
