### ISSUE TITLE
Placing MediaQueryList in app.razor

### ISSUE THREAD

**Issue by aterbo** [EdCharbeneau/BlazorSize#77]
Hi Ed,

I ran into a bug using BlazorSize in conjunction with [Blazored Modals](https://github.com/Blazored/Modal) which I believe is due to where the cascading modal wrappers are placed.

Blazored Modals work by wrapping the `<Router>` in `App.razor` in a `<CascadingBlazoredModal>` component, which handles various things for calling and displaying modals. 

Per the BlazorSize wiki, I initially wrapped the `MainLayout.razor` in the `<MediaQueryList>`. This worked until I called a Blazored Modal that called the MediaQuery within it. I then got a null exception on my `MediaQueryList` object.

To correct this, I changed the location of `<MediaQueryList>` to be in `App.razor` as well. Now, my `App.razor` is structured like this:

```razor
<CascadingAuthenticationState>
   <MediaQueryList>
        <CascadingBlazoredModal>
            <Router AppAssembly="@typeof(Program).Assembly" PreferExactMatches="@true">

                @*Router things here*@

            </Router>
        </CascadingBlazoredModal>
    </MediaQueryList>
</CascadingAuthenticationState>
```

This appears to function as intended, but I don't know enough about the inner workings of BlazorSize to know if this is an appropriate use.

Will I cause anything to break by wrapping the router in this fashion? Am I missing something in my testing?

Thanks,
Andy

**Comment by EdCharbeneau** [comment]
This should work fine. The reason BlazorSize wasn't working with the modal is the Modal probably renders outside the MainLayout using the `<CascadingBlazorModal>` component as its render location, therefore it exists as a parent to MainLayout.

App.razor is the absolute root component in the application, it should work fine here. Please reopen the issue if something else comes up.

**Comment by aterbo** [comment]
Thanks, Ed! I get a little hesitant if something works but I'm using it in a way that is different than the docs.
