### ISSUE TITLE
Javascript Exception when Refreshing Page

### ISSUE THREAD

**Issue by lassanter** [EdCharbeneau/BlazorSize#85]
Good day!  

I am having an issue where everything functions normally when initially loading a component. However, when I click the browser's refresh button, I get this JS exception:  

> [2022-12-23T12:11:56.095Z] Error: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
> 
>    at BlazorPro.BlazorSize.MediaQueryService.Initialize(MediaQuery mediaQuery)
> 
>    at BlazorPro.BlazorSize.MediaQueryList.Initialize(MediaQuery mediaQuery)
> 
>    at BlazorPro.BlazorSize.MediaQuery.OnAfterRenderAsync(Boolean firstRender)
> 
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState) [blazor.server.js:1:116297](https://localhost:7273/_framework/blazor.server.js)
>     log https://localhost:7273/_framework/blazor.server.js:1
>     tr https://localhost:7273/_framework/blazor.server.js:1
>     er https://localhost:7273/_framework/blazor.server.js:1
>     _invokeClientMethod https://localhost:7273/_framework/blazor.server.js:1
>     _invokeClientMethod https://localhost:7273/_framework/blazor.server.js:1
>     _processIncomingData https://localhost:7273/_framework/blazor.server.js:1
>     onreceive https://localhost:7273/_framework/blazor.server.js:1
>     onmessage https://localhost:7273/_framework/blazor.server.js:1  
  
This behavior occurs primarily in Firefox (I do not see it in Chrome most of the time, though it has been reported by testers at least once).  
  
I have trimmed the component down to JUST the MediaQuery tag (Breakpoints.MediumUp) with a Matched and Unmatched tag, and within each an empty div. The exception is still thrown. As soon as I remove the MediaQuery tag the exception goes away.  
  
What makes this infuriating to diagnose is that it only happens on ONE particular component. There are numerous other component that use the MediaQuery tag but do not display this behavior. I have not been able to isolate the issue, yet, beyond the use of MediaQuery.  
  
It should also be noted, I think, that it does not occur on my mobile device, nor when I have Firefox in mobile mode.

**Comment by EdCharbeneau** [comment]
There have been a few issues raised of isolated cases where js throws errors. I haven't been able to reproduce them on my end, they're very intermittent. I've seen some correlation with Blazor Server, are you using WASM?

These issues don't come up in e2e, and I can't seem to recreate them.

**Comment by lassanter** [comment]
My apologies for not noting that.  
  
I am using Blazor Server.

**Comment by robi26** [comment]
Seeing the same problem, also using blazor server.

**Comment by EdCharbeneau** [comment]
I just released a new version, I don't feel like it will address this issue but I will begin investigating this issue next.

**Comment by gragra33** [comment]
@lassanter do you have a minimal sample app that can produce the problem? Is there a set of steps other than refreshing the browser that is needed?

**Comment by lassanter** [comment]
Sadly, as noted above, I have not been able to isolate the issue. The it is pretty consistent on two specific pages, but no problem at all anywhere else.

**Comment by gragra33** [comment]
I would love to help with this, however, @lassanter without access to the code with the issue, only you can reproduce and isolate it. If the steps to reproduce the issue are known, then a fix is possible.

**Comment by EdCharbeneau** [comment]
I believe this issue was addressed in 6.2.0. Please reopen of it was not resolved.
