### ISSUE TITLE
Add more example for MediaQuery in documentation?

### ISSUE THREAD

**Issue by Stardusstt** [EdCharbeneau/BlazorSize#87]
Maybe we can add more examples for MediaQuery of other uses? like [this](https://github.com/EdCharbeneau/BlazorPowerHour/blob/d955992e4f032e37fea2bdb98aa27849528ce2ec/EP11-17-ThemeSwap/Shared/MainLayout.razor#L17)
When I first saw the documentation, I thought it could only listening for Breakpoints.
```html
<MediaQuery Media="(prefers-color-scheme: dark)" @bind-Matches="isDark" />
```

**Comment by EdCharbeneau** [comment]
Great suggestion, thank you.

**Comment by EdCharbeneau** [comment]
Added to Wiki https://github.com/EdCharbeneau/BlazorSize/wiki/BlazorSize-knowledge-base#accessibilitymediatypes-media-query-support
